# Generated by Django 6.0.4 on 2026-04-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('no_match', 'Sin coincidencia'), ('error', 'Error')], max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('match_timestamp_seconds', models.FloatField(blank=True, null=True)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song_matched', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='songs.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
