# Generated by Django 6.0.4 on 2026-05-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='method',
            field=models.CharField(choices=[('audio', 'Audio'), ('text', 'Texto'), ('humming', 'Tarareo')], default='audio', max_length=10),
        ),
    ]
